version: '3'
services:
  # To start the development server
  web-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8088:3000'
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    stdin_open: true
  # To run the tests
  tests:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]
